### ISSUE TITLE
Re: Doubt

### ISSUE THREAD

**Issue by ggautham** [ranandiitk/zomato#1]
Hey , 

I tried using your code for retrieving data from Zomato website .. I am getting the following message :+1: 

{u'status': u'Not Allowed, Please request for partner access'}

Can you help me on this .

My email id is ggautham10@gmail.com
 Mail me so that we can talk further about this.

Thanks

**Comment by dotRData** [comment]
key        <<- '07b65c0fd9ac93e8c6bb905f468eaa14'

This is key has expired, you can request new key here "https://developers.zomato.com/api#headline2"
And use it in R code, python code is not yet complete.

**Comment by ggautham** [comment]
I requested a new key and am working with that .. But still it throws the same error for me.. Moreover I have to work with python only .. Could u help on this .

-----Original Message-----

**Comment by dotRData** [comment]
Zomato has changed their policy, now only Partners can access the review data
https://developers.zomato.com/documentation#/

Under reviews
Implementation Notes: Partner Access Get restaurant reviews using the Zomato restaurant ID.

I am a partner so, I have a separate key for accessing. I think you have to request partner access.
Sorry.

**Comment by ggautham** [comment]
Thank you :) The issue got resolved now . Just a small clarification , only 20 records are displayed for each query , is there any way to increase the number of records that are being displayed.

**Comment by dotRData** [comment]
For that also you need to have extra access, with general access you can
get 10 output at a time with 2 query it will be 20 by changing start date
for one restaurant review.

**Comment by ggautham** [comment]
Hi , 

A small clarification again , i was working with the GET/search API of zomato , as given in the model response , i am not able to retreive all_reviews dictionary , i dont know the reason for it . Could you help me to know what might be the cause. I am not sure if its something related to partner's access. 
I want to retreive the review_text from the all_reviews dictionary for my project . 

Kindly help me on this .

Regards,
Gautham
